from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel
import yt_dlp
import os
import tempfile
from urllib.parse import urlparse

app = FastAPI()

class ExtractReq(BaseModel):
    url: str
    cookies: str = None

@app.post("/extract")
async def extract(req: ExtractReq, x_api_key: str = Header(None)):
    if x_api_key != "Liyifeng11":
        raise HTTPException(status_code=401, detail="Unauthorized")
    
    ydl_opts = {
        'quiet': True,
        'no_warnings': True,
        'format': 'best',
        'nocheckcertificate': True,
    }

    # 🚀 增强版 Cookie 处理：生成 Netscape 格式文件
    tmp_path = None
    if req.cookies and len(req.cookies) > 10:
        try:
            # 自动识别域名，确保 Cookie 对应关系正确
            domain = urlparse(req.url).netloc
            if domain.startswith("m."): domain = domain[2:]
            if domain.startswith("www."): domain = domain[4:]
            
            # 创建临时文件
            fd, tmp_path = tempfile.mkstemp(suffix=".txt")
            with os.fdopen(fd, 'w') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by YT Extractor\n")
                
                # 解析 App 传来的 name=value; 字符串
                pairs = req.cookies.split(';')
                for pair in pairs:
                    if '=' in pair:
                        name, value = pair.strip().split('=', 1)
                        # 构造 Netscape 格式行 (Domain, Include subdomains, Path, Secure, Expiry, Name, Value)
                        f.write(f".{domain}\tTRUE\t/\tTRUE\t2147483647\t{name}\t{value}\n")
            
            # 让 yt-dlp 使用这个临时文件
            ydl_opts['cookiefile'] = tmp_path
            print(f"🍪 [Backend] Cookie file generated for {domain}")
            
        except Exception as e:
            print(f"❌ [Backend] Cookie generation failed: {e}")

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(req.url, download=False)
            return {
                "title": info.get('title'),
                "play_url": info.get('url'),
                "thumbnail": info.get('thumbnail'),
                "duration": info.get('duration')
            }
    except Exception as e:
        error_msg = str(e)
        print(f"❌ [Backend] Extraction failed: {error_msg}")
        raise HTTPException(status_code=500, detail=error_msg)
    finally:
        # 清理临时文件，防止泄露隐私或占用空间
        if tmp_path and os.path.exists(tmp_path):
            try:
                os.remove(tmp_path)
            except:
                pass

@app.get("/health")
async def health():
    return {"status": "ok", "engine": "yt-dlp"}
